# Generated by Django 4.1.2 on 2022-10-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='apellido',
            field=models.CharField(default='Valid', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiar',
            name='localidad',
            field=models.CharField(default='Morteros', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familiar',
            name='direccion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
